### PR TITLE
[issue/5] allow operator control of PAM service name against which us…

### PR DESCRIPTION
**Pull request by ae6rt**
[issue/5] allow operator control of PAM service name against which users are authenticated

### CODE REVIEW

**Comment by bjhaid** [comment]
you need to set the service name in the stub config here:

https://github.com/bjhaid/pam_hook/blob/4566a74a6de9272296d98360bbdfd33423c712dd/main_test.go#L24-L28

that should make the tests happy

**Comment by ae6rt** [comment]
Sorry for the churn.  Made the change, PTAL.

**Comment by bjhaid** [comment]
thanks alot!

**Comment by ae6rt** [comment]
Thank you for taking the PR.

**Pull request merged**
